spring:
  application:
    name: lms
  datasource:
    url: "jdbc:mysql://localhost:3306/project3"
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  servlet:
    context-path: /api/v1

security:
  jwt:
    secret: change-me-please-32-chars-min
    access-token-expiration-ms: 10800000   # 3 hours
    refresh-token-expiration-ms: 1209600000 # 14 days
    issuer: lms-service
  role-mapping:
    location: classpath:role.properties

file:
  storage:
    provider: MINIO # LOCAL | MINIO | S3
    public-base-url: http://localhost:9000/lms-files/
    s3:
      endpoint: http://localhost:9000
      region: us-east-1
      access-key: minioadmin
      secret-key: minioadmin123
      bucket: lms-files
      path-style-access: true
      public-base-url: http://localhost:9000/lms-files/
    presign:
      put-expiry-seconds: 600
      get-expiry-seconds: 300

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

payment:
  vnpay:
    tmnCode: D5V6VHEW
    hashSecret: EW1B251M7TXF2ZKS7NQLBN072CS6OGDZ
    payUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    returnUrl: http://localhost:5173/payment/return   # placeholder FE URL
    ipnUrl:  https://735dc5800d55.ngrok-free.app/api/v1/payments/vnpay/ipn
    currency: VND
    locale: vn
    client-ip: 8.8.8.8         # do not use localhost for VNPay
    expire-minutes: 15         # payment link TTL for vnp_ExpireDate
